Add missing System.Linq using directive
Fix compilation error: 'IEnumerable<RefSpec>' does not contain a definition for 'Select'
Added: using System.Linq; (line 3)

The Select() method is a LINQ extension method that requires System.Linq namespace.